### PR TITLE
Fix cost assumptions

### PR DESCRIPTION
**Pull request by Danice123**
#25

### CODE REVIEW

**Review by TNychka — APPROVED** [review]
LGTM, but I'll need to test it first before I can merge it

**Comment by Danice123** [comment]
Oh how I love removing lines of code

**Comment by Danice123** [comment]
@TNychka I tested this fully, and found a couple weapons that don't have their configs set haha. But the code doesn't crash so we're good

**Comment by TNychka** [comment]
Sounds good. The only reason I ask is that I can't actually verify other people have tested.

**Comment by Danice123** [comment]
Honestly I didn't seriously test it until now

**Pull request merged**
