### PR TITLE
Fixing Unicode issues for Localization files

### PR DESCRIPTION
**Pull request by Danice123**
I'm making a separate pull request for this, it will be easier to merge this way.

### CODE REVIEW

**Review by TNychka — CHANGES_REQUESTED** [review]
Can you add all of the localization files?

**Comment by Danice123** [comment]
Add them? They didnt change?

**Comment by TNychka** [comment]
Yeah, but all of the translation extensions in the localizations folder will probably have the same issue. 
.chn
.jpn
.rus
ect. so we might as well add them in now

**Comment by Danice123** [comment]
Oh right I see

**Comment by Danice123** [comment]
Added them

**Pull request merged**
