### PR TITLE
Missing Trading Post/Ipoints Values fixes #26

### LINKED ISSUE #26: Missing configuration for weapons
\*\_\*\_TRADINGPOSTVALUE
and
\*\_\*\_IPOINTS
exist but are not implemented.

\*\_LASER_ISUPPLIES
exists but seems to be a stub from wotc's code, so probably could get rid of it?

### PR DESCRIPTION
**Pull request by Derseboom**
Altered weapon values according to instruction.

I.E. added (WEAPON_TIER_TRADINGPOST/IPOINTS = X) to all files that hadn't been updated. Also fixed a small inconsistency in upgrade slots on the Laser Vektor Rifle.

https://github.com/X2LongWarOfTheChosen/LWOTC_WeaponPack/issues/26

### CODE REVIEW

**Comment by Derseboom** [comment]
Missing template reference values at the bottom of the page for all weapons, will tackle the issue tomorrow as a separate project.

**Comment by TNychka** [comment]
@Derseboom please submit a new issue for that issue and then we can get to it. Any issues you find just drop a new issue on the issue list.

**Review by TNychka — APPROVED** [review]

**Comment by TNychka** [comment]
completed in Assorted bug fixes #47

**Comment by Derseboom** [comment]
Missing template reference values at the bottom of the page for all weapons, will tackle the issue tomorrow as a separate project.

**Comment by TNychka** [comment]
@Derseboom can you submit a new issue and PR for that? Thanks!

**Pull request merged**
